[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scriptcheck"
description = "Print a list of scripts from your Python Scripts folder for when you're like me and can't remember what you've installed or what a tool is called."
version = "0.0.1"
requires-python = ">=3.10"
dependencies = ["pathier", "younotyou", "pytest"]
readme = "README.md"
keywords = []
classifiers = ["Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent"]

[[project.authors]]
name = "Matt Manes"
email = "mattmanes@pm.me"

[project.urls]
Homepage = "https://github.com/matt-manes/scriptcheck"
Documentation = "https://github.com/matt-manes/scriptcheck/tree/main/docs"
"Source code" = "https://github.com/matt-manes/scriptcheck/tree/main/src/scriptcheck"

[project.scripts]
scriptcheck = "scriptcheck.scriptcheck:main"

[tool]
[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
pythonpath = "src"

[tool.hatch.build.targets.sdist]
exclude = [".coverage", ".pytest_cache", ".vscode", "tests", ".gitignore"]
