[tool.poetry]
name = "md-protobuf"
version = "2.0.0"
description = "md-protobuf provides a Markdown interface to Google's Protocol Buffers"
readme = "README.md"
license = "Apache 2"
authors = [
    "Michael Medin <michael@medin.name>"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.0"
protobuf = ">=3.0.0"


[project.urls]
Documentation = "http://github.com/mickem/md-protobuf"
Source = "http://github.com/mickem/md-protobuf"
Issues = "http://github.com/mickem/md-protobuf/issues"
History = "http://github.com/mickem/md-protobuf"

[tool.poetry.scripts]
protoc-gen-md = "md_protobuf:main"

