# Specify the build system for the project.
[build-system]
requires = ["sip >=6, <7", "PyQt-builder >=1.10, <2"]
build-backend = "sipbuild.api"

# Specify the PEP 566 metadata for the project.
[tool.sip.metadata]
name = "PyQt6-DataVisualization"
version = "6.6.0"
summary = "Python bindings for the Qt Data Visualization library"
home-page = "https://www.riverbankcomputing.com/software/pyqtdatavisualization/"
author = "Riverbank Computing Limited"
author-email = "info@riverbankcomputing.com"
license = "GPL v3"
description-file = "README"
requires-dist = "PyQt6 (>=6.2.0)"

# Specify a PyQt-based project.
[tool.sip]
project-factory = "pyqtbuild:PyQtProject"

# Configure the project.
[tool.sip.project]
tag-prefix = "QtDataVisualization"

# Define and configure each set of bindings.
[tool.sip.bindings.QtDataVisualization]
qmake-QT = ["datavisualization"]
