# Where to save the log file; this can be an absolute or relative path.
# Leave as "" to not generate a log file.
# Default: ""
log_file = ""

# At what level to print log messages.
# 10 - debug, 20 - info, 30 - warn, 40 - error, 50 - critical
# Default: 20
log_level = 20

# Show version of LetterBomb module in bottom-left corner of webpage?
# Might be a small vulnerability if an old version has a security issue, and you aren't updated yet.
# Default: false
show_version = false

# Show sublinks below the LetterBomb logo?
# Default: true
show_sublinks = true

# Show a ribbon advertising forking in the top-right corner of webpage
# Default: True
show_ribbon = false

# Fill these in if you intend on having a Captcha.
# Leave *BOTH* of these blank if you do not want to include a Captcha.
# Default: "", ""
captcha_public_key = ""
captcha_private_key = ""

debug = false