[tool.poetry]
name = "dwave-sona-core"
version = "1.1.8"
description = ""
authors = ["dwave-dev"]
license = ""
readme = "README.md"
packages = [{include = "sona"}]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.28.62"
confluent-kafka = "^2.2.0"
fastapi = "^0.103.2"
google-api-python-client = "^2.102.0"
loguru = "^0.7.2"
opentelemetry-api = "^1.18.0"
opentelemetry-sdk = "^1.18.0"
opentelemetry-exporter-jaeger-thrift = "^1.18.0"
pydantic = "^2.4.2"
pydantic-settings = "^2.0.3"
python-ffmpeg = "^2.0.4"
redis = "^5.0.1"
requests = "^2.31.0"
typer = "^0.9.0"
uvicorn = "^0.23.2"
wget = "^3.2"
yt-dlp = "^2023.3.4"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
