[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MagneticReadoutProcessing"
authors = [{name = "Marcel Ochsendorf", email = "info@marcelochsendorf.com"}]
dynamic = ["version", "description", "dependencies"]
requires-python = ">=3.7"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.scripts]
MRPCli = "MRPcli.cli:run"
MRPUDPP = "MRPudpp.udpp:run"


[project.urls]
"Homepage" = "https://github.com/LFB-MRI/MagneticReadoutProcessing"
"Bug Tracker" = "https://github.com/LFB-MRI/MagneticReadoutProcessing/issues"
"Documentation" = "https://magneticreadoutprocessing.readthedocs.io/en/latest/"

