[tool.poetry]
name = "producer-consumer-hassou-karim"
version = "0.1.1"
description = ""
authors = ["Hassou Karim <hassoukarim@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9, <3.12"
numpy = "^1.26.1"
pandas = "^2.1.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
black = "^23.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"