[project]
name = "lib-munpy"
version = "0.1.1"
dynamic = ["dependencies"]
description = "Library to preprocess the inputs for MUNICH dispersion model and postprocess its outputs"

[tool.setuptools.packages]
find = {}

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
