[tool.poetry]
name = "rnd-logger"
version = "1.2.1"
description = "Made Tech R&D Logger"
authors = ["Made Tech R&D Engineering <rnd-engineering@madetech.com>"]
readme = "README.md"
packages = [{include = "rnd_logger"}]

[tool.poetry.dependencies]
python = "^3.11"
sentry-sdk = "^1.32.0"
python-json-logger = "^2.0.7"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"