[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "is_that_you"
version = "0.0.1"
authors = [
  { name="megahomyak", email="g.megahomyak@gmail.com" },
]
description = "A vtuber program with emotion recognition"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ['opencv_python == 4.8.1.78', 'fer == 22.5.1', 'tensorflow >= 1.7', 'pyvirtualcam == 0.9.1', 'numpy == 1.22.0', 'sounddevice >= 0.4.6, < 0.5.0', 'Pillow >= 10.1.0, < 11.0.0']

[project.urls]
"Homepage" = "https://github.com/megahomyak/is_that_you"
