[tool.poetry]
name = "marketpanda"
version = "0.1.7"
description = "MarketVault access library"
authors = ["Fayssal El Mofatiche <fayssal.elmofatiche@dnbf.tech>"]
readme = "README.md"
license = "MIT"
packages = [
    { include = "marketpanda", from = "." }
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pandas = "^2.1.1"
requests = "^2.31.0"
cpi = "^1.0.21"
gdown = "^4.7.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
requests-mock = "^1.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
