# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autogram"
version = "3.4.3"
description = "An easily extensible telegram API wrapper"
readme = "README.md"
authors = [{ name = "sp3rtah", email = "ngaira14nelson@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["telegram", "API", "wrapper"]
dependencies = [
	"SQLAlchemy==2.0.19",
	"loguru==0.7.0",
	"bottle==0.12.25",
	"requests==2.31.0",
]
requires-python = ">=3.6"

[project.optional-dependencies]
dev = ["build", "twine"]

[project.urls]
Homepage = "https://github.com/sp3rtah/autogram"
