# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "array-cache"
version = "1.0.0"
description = "Cache the current index of you array"
readme = "README.md"
authors = [{ name = "n4n5", email = "its.just.n4n5@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["cache", "array", "array-cache", "array_cache", "arraycache"]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/Its-Just-Nans/array-cache"
"Bug Tracker" = "https://github.com/Its-Just-Nans/array-cache/issues"
