[tool.poetry]
name = "yaml-dataclass"
version = "0.1.2"
description = "Simple Settings Base Class for Handling YAML settings"
authors = ["Gereon Tombrink <tombrink@igg.uni-bonn.de>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.2,<3.12"
PyYAML = ">=6.0.1"
pydantic = "^2.4.2"
colorama = "^0.4.6"

[tool.poetry.group.dev.dependencies]
mypy = "^1.5.1"
black = "^23.9.1"

[tool.isort]
profile = "black"
line_length = 119

[tool.black]
line-length = 119

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
