[project]
name = "MattZeta"
version = "0.2"
authors = [
  { name="Matthew Perkins", email="matthew.perkins@mssm.edu" },
  ]
  description = "ZETA test for neurons, more faster."
  readme = "README.md"
  requires-python = ">=3.8" # not sure about this? tested on 3.11 only
  classifiers = [
      "",
	      ]
dependencies = [
	     'numpy',
	     'matplotlib',
	     'scipy',
	     'numba',
	     ]	      

[project.urls]
"Homepage" = "https://github.com/matthewperkins/MattZeta"
"Bug Tracker" = "https://github.com/matthewperkins/MattZeta/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
