[build-system]
requires = ["setuptools>=59.6"]
build-backend = "setuptools.build_meta"

[project]
name = "matrix-linalg"
version = "0.0.2"
authors = [
    { name="John Chesser", email="johndc93@gmail.com" }
]
description = "a small class to implement matrix operations for Math 322"
readme = "README.md"
requires-python = "~=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = ["tabulate~=0.9"]


[project.urls]
"Homepage" = "https://github.com/j-chess/matrix-linalg"
"Bug Tracker" = "https://github.com/j-chess/matrix-linalg/issues"