[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arcusapi"
version = "0.1.9"
authors = [
  { name="Arcus Inc.", email="sdk@arcus.co" },
]
description = "Arcus Data Platform Client SDK."
readme = "README.md"
requires-python = ">=3.8,<4.0"
dependencies = [
  "numpy>=1.23",
  "langchain>=0.0.175",
  "openai>=0.27.2",
  "requests>=2.28.0",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
torch = [
  "torch==1.13.1",
  "pytorch-lightning==1.9.3"
]
lightgbm = [
  "lightgbm==4.1.0",
  "pandas==1.5.3"
]
all = [
  "torch==1.13.1",
  "pytorch-lightning==1.9.3",
  "lightgbm==4.1.0",
  "pandas==1.5.3"
]

[project.urls]
"Homepage" = "https://www.arcus.co"
"Documentation" = "https://app.arcus.co/docs"
