repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'pylint "$@"'
        language: system
        verbose: true
        types: [python]
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=pylintrc",
            "--jobs=0",
            "--output-format=colorized",
            "--msg-template='{msg_id}:{line:4d}: [{obj}] {msg}'"
          ]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/
  - repo: git@bitbucket.org:paraty/check_with_last_score_python2.git
    rev: latest
    verbose: true
    hooks:
      - id: check_with_last_score_python2
        stages: [commit]
        verbose: true
        additional_dependencies: [pylint==1.9.5, GitPython, colorama, tabulate==0.8.10]
