[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "calcat"
version = "1.0.1"
authors = [
  { name="Agnieszka Thiel", email="ag.thiel.arc@gmail.com" }
]
description = "A Python package for basic arithmetic operations."
readme = "README.md"
requires-python = ">=3.9.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
homepage = "https://github.com/TuringCollegeSubmissions/athiel-DWWP.1.5"
bugtracker = "https://github.com/TuringCollegeSubmissions/athiel-DWWP.1.5/issues"