[tool.poetry]
name = "repotracer"
version = "0.3.0"
description = "A tool to collect statistics about a git repository over time"
authors = ["Amedee d'Aboville <amedee.daboville@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
repotracer = "repotracer.main:app"

[tool.poetry.dependencies]
s3fs = "^2023.6.0"
python = "^3.11"
pandas = "^1.5.3"
tqdm = "^4.64.1"
sh = "^2.0.4"
typer = {extras = ["all"], version = "^0.9.0"}
json5 = "^0.9.14"
pydantic = "^2.1.1"
matplotlib = "^3.7.2"
seaborn = "^0.12.2"
questionary = "^2.0.0"
dacite = "^1.8.1"
pytest = "^7.4.3"
pytest-cov = "^4.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
