[project]
name = "loadingpy"
version = "0.0.5"
description = "fancy progress bar"
authors = [
    {name = "Edouard Yvinec", email="edouardyvinec@hotmail.fr"}
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3"
]


[build-system]
requires = ["setuptools>=42",]
build-backend = "setuptools.build_meta"
