[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dislord"
version = "0.0.1"
authors = [
  { name="Jack Draper", email="drapj002@gmail.com" },
]
description = "A serverless optimized discord API library using interactions."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/JayDwee/dislord"
"Bug Tracker" = "https://github.com/JayDwee/dislord/issues"