[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "drp_package"
version = "0.5.7"
description = ""
authors = [ "Your Name <you@example.com>",]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = ">=1.13.3"
ortools = "9.7.2996"
matplotlib = "3.7.1"
