[tool.poetry]
name = "pydataconn"
version = "0.1.2"
description = "Python Data Connection"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
google-api-python-client = "^2.30.0"
google-auth-httplib2 = "^0.1.1"
google-auth-oauthlib = "^1.1.0"
xds-protos = "^1.59.0"
pendulum = "^2.1.2"
pygsheets = "^2.0.6"
pandas = "^2.1.2"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"