[build-system]
requires = ["setuptools>=67.7.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kaftar"
version = "0.0.4"
authors = [
  { name="Amirreza Taherkhani", email="amirrezataherkhaani@gmail.com" },
]
description = "a simple sdk to send notifications on queue for celery tasks"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"