[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "loggi"
description = "logger boilerplate with dataclass models for parsing"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pathier", "typing_extensions", "younotyou", "pytest"]
readme = "README.md"
keywords = ["log", "logger", "logging"]
classifiers = ["Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent"]

[[project.authors]]
name = "Matt Manes"
email = "mattmanes@pm.me"

[project.urls]
Homepage = "https://github.com/matt-manes/loggi"
Documentation = "https://github.com/matt-manes/loggi/tree/main/docs"
"Source code" = "https://github.com/matt-manes/loggi/tree/main/src/loggi"

[project.scripts]

[tool]
[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
pythonpath = "src"

[tool.hatch.build.targets.sdist]
exclude = [".coverage", ".pytest_cache", ".vscode", "tests", ".gitignore"]
