[tool.poetry]
name = "hypersphere"
version = "0.1.0"
description = "Проект для работы с данными, распределенными на поверхности гиперсферы."
authors = ["Radik Ismagilov <radik@td.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
numpy = "1.26.1"
scikit-learn = "1.3.2"
matplotlib = "3.8.0"
ipympl = "0.9.3"

[tool.poetry.group.dev.dependencies]
pandas = "2.1.1"
scipy = "1.11.3"
tqdm = "4.66.1"
geomstats = "2.7.0"

[tool.poetry.group.test.dependencies]
black = {extras = ["jupyter"], version = "23.9.1"}
isort = "5.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
