[tool.poetry]
name = "genut-py"
version = "0.1.2"
description = ""
authors = ["Eiichiro Sato <gasinsato@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "genut_py"}]

[tool.poetry.dependencies]
python = "^3.10"
coverage = "7.3.2"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.10.0"
flake8 = "^6.1.0"
pyproject-flake8 = "^6.1.0"
pytest = "^7.4.3"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-rtd-theme = "^1.3.0"

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
line_length = 99

[tool.flake8]
max-line-length = 99

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
