[tool.poetry]
name = "prime_as6723"
version = "1.2.0"
description = "Package with the is_prime function and some tests!"
authors = ["Arushi Saranath"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<4"
myst-nb = "0.17.2"
sphinx-autoapi = "2.x.x"  # Replace '2.x.x' with the highest compatible version
sphinx-rtd-theme = "1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



