[build-system]
requires = ["setuptools",'requests']
build-backend = "setuptools.build_meta"

[project]
name = "Titanpy"
version = "0.0.9"
authors = [
  { name="Dylan Rose", email="dylantrose@gmail.com" },
]
description = "Servicetitan API Package tool"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pabboat/Titanpy"
"Bug Tracker" = "https://github.com/pabboat/Titanpy/issues"