[project]
name = "simplex-api"
version = "0.0.3"
authors = [
  { name="Marco Nocito", email="mnocito@mit.edu" },
]
description = "Simplex core api for managing simulations."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/mnocito/simplex-api"