[tool.poetry]
name = "data2df"
version = "0.0.1a2"
description = "Unified interface to connect common data sources in Data Science with common dataframe packages"
authors = ["Claudio Chiappetta <cl4udio.chiappetta@gmail.com>"]
readme = "README.md"

[tool.ruff]
ignore-init-module-imports = true

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
ruff = "^0.1.3"
black = "^23.10.1"
pytest = "^7.4.3"
pytest-lazy-fixture = "^0.6.3"

[tool.poetry.group.pandas]
optional = true
[tool.poetry.group.pandas.dependencies]
pandas = "^2.1.2"

[tool.poetry.group.db]
optional = true
[tool.poetry.group.db.dependencies]
sqlalchemy = "<2.0"
sqlalchemy-vertica = {extras = ["vertica-python"], version = "^0.0.5"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
