[tool.poetry]
name = "deciphon-sched"
version = "0.11.1"
description = "Deciphon scheduler"
authors = ["Danilo Horta <horta@ebi.ac.uk>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = { extras = ["all"], version = "^0.101.1" }
fasta-reader = "^3"
uvicorn = { extras = ["standard"], version = "^0" }
sqlalchemy = "^2"
pydantic-settings = "^2"
boto3 = ">=1.28.32,<1.29"
pydantic = "^2"
aiomqtt = "^1"
deciphon-core = "^0"
loguru = "^0"
testcontainers = { version = "^3", optional = true }
testcontainers-core = { version = "^0", optional = true }
testcontainers-minio = { version = "^0", optional = true }
python-multipart = "^0"
deciphon-snap = "^0"
# https://github.com/orgs/python-poetry/discussions/7937#discussioncomment-5921842
urllib3 = "<2"
typer = "^0.9.0"

[tool.poetry.extras]
testing = ["testcontainers", "testcontainers-core", "testcontainers-minio"]

[tool.poetry.group.dev.dependencies]
pytest = "^7"
pytest-asyncio = "^0"
requests = "^2"
paho-mqtt = "^1"
testcontainers = "^3"
testcontainers-core = "^0"
testcontainers-minio = "^0"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poetry.scripts]
deciphon-sched = 'deciphon_sched.cli:app'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
