[project]
name = "flazsurvey"
version = "0.0.4"
authors = [
  { name = "Alexander Schau", email="alexander@schau.email" },
]
description = "work in progress"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://flaz.it"