[project]
name = "math_sequence"
version = "0.0.2"
authors = [
  { name="Ashish Mukherjee", email="ashishmukherjee@protonmail.com" },
]
description = "Package to generate commonly used number sequences"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/ashish-m-yh/math/tree/main/math_sequence"
"Bug Tracker" = "https://github.com/ashish-m-yh/math/issues"
