[project]
name = "scientific_plots"
requires-python = ">=3.8"
description = "Useful methods for plots used in science"
readme = "readme.md"
authors = [{name = "Felix Fischer", email = "f.fischer@ifas.rwth-aachen.de"}]
classifiers = [
    """License :: OSI Approved :: \
    GNU Lesser General Public License v3 or later (LGPLv3+)""",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3"
]
keywords = ["Plotting", "science", "library", "utilities", "styling"]

license = {file = "COPYING.LESSER"}

dependencies = [
    "scipy",
    "numpy>=1.21",
    "matplotlib>=3.7",
    "SciencePlots",
    "python_translator",
    "requests",
    "beautifulsoup4",
    "urllib3>=2.0.0"
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "mypy",
    "pylint",
    "flake8",
    "pytest",
    "types-urllib3",
    "twine>=4.0.0",
    "requests-toolbelt>=1.0.0"
]

[build-system]
requires = ["setuptools>42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-data = {"*" = [
    "py.typed",
    "readme.md",
    "*.pyi",
    "COPYING.LESSER"]}

[tool.setuptools.dynamic]
version = {attr = "scientific_plots.__version__"}

[tool.mypy]
python_version = "3.9"
warn_unused_configs = true
follow_imports_for_stubs = true
warn_redundant_casts = true
strict = true
warn_unused_ignores = false

[tool.pylint.MASTER]
fail-under = 9.0

[tool.pylint.BASIC]
good-names = ["i", "j", "k", "ex", "Run", "_", "ax", "e", "f", "n", "N",
              "M", "q", "C", "A", "R", "d"]
good-names-rgxs = "_?[xXyYzZ]\\d?"

[tool.pylint.DESIGN]
max-args = "8"

[tool.pytest.ini_options]
markers = [
    "use_style: These test use the style 'science'"
]
